import { useState } from "react";import type { Run } from "../data/mock";
function fmt(ms:number){return ms<1000?`${ms} ms`:`${(ms/1000).toFixed(1)} s`}
export function ResultView({run}:{run:Run}){const[open,setOpen]=useState(true);const finished=run.state==="done"||run.state==="blocked";return <section aria-label="Result" className="result-section">
 <div className="flex items-baseline justify-between gap-4"><p className="eyebrow">{run.state==="blocked"?"Stopped":"Result"}</p><span className="font-mono text-[11px] text-faint">{run.receipt} · SAMPLE</span></div>
 {finished?<p className="mt-4 max-w-[62ch] text-[17px] leading-[1.65] tracking-[-0.01em] text-text">{run.summary}</p>:<p className="mt-4 text-[16px] text-muted">Working through the task. Evidence appears as it lands.</p>}
 <ol className="mt-6 border-t border-line" aria-label="Evidence">{run.steps.map(s=><li key={s.id} className="evidence-row"><span className={`mt-2 h-1.5 w-1.5 shrink-0 rounded-full ${s.ok?"bg-done":"bg-danger"}`}/><div className="min-w-0 flex-1"><p className="text-sm text-text">{s.name}</p><p className="mt-0.5 text-xs leading-relaxed text-muted">{s.detail}</p></div><span className="shrink-0 font-mono text-[11px] text-faint">{fmt(s.durationMs)}</span></li>)}{run.steps.length===0&&<li className="py-4 text-sm text-muted">No evidence yet.</li>}</ol>
 {finished&&run.steps.length>0&&<div className="border-t border-line"><button type="button" aria-expanded={open} onClick={()=>setOpen(!open)} className="verification-toggle"><span>Verification <span className="text-faint">{run.steps.filter(s=>s.ok).length}/{run.steps.length} passed</span></span><svg width="10" height="6" viewBox="0 0 10 6" className={`transition-transform ${open?"rotate-180":""}`}><path d="M1 1l4 4 4-4" stroke="currentColor" strokeWidth="1.4" fill="none" strokeLinecap="round"/></svg></button>{open&&<dl className="verification-grid"><div><dt>Run time</dt><dd>{fmt(run.durationMs)}</dd></div><div><dt>Model</dt><dd>{run.model}</dd></div><div><dt>Started</dt><dd>{run.startedAt}</dd></div></dl>}</div>}
 <p className="mt-6 text-xs leading-relaxed text-faint">Preview only. No backend is connected, so this is sample interface data, not real agent output.</p>
 </section>}
