import { chromium } from 'playwright';
import fs from 'node:fs';
const out='verification/fast-mode-v2';
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1280,height:820},recordVideo:{dir:out,size:{width:1280,height:820}}});
await page.goto('http://127.0.0.1:4173');
await page.screenshot({path:`${out}/01-standard-before.png`});
const fast=page.getByRole('button',{name:/Fast mode/i});
await fast.click();
await page.waitForTimeout(300); await page.screenshot({path:`${out}/02-compress.png`});
await page.waitForTimeout(220); await page.screenshot({path:`${out}/03-accelerate.png`});
await page.waitForTimeout(600); await page.screenshot({path:`${out}/04-fast-standard.png`});
await page.getByRole('button',{name:/Ultra mode/i}).click(); await page.waitForTimeout(1300);
await page.screenshot({path:`${out}/05-fast-ultra.png`});
const checks={};
checks.fastPressed=await fast.getAttribute('aria-pressed');
checks.ultraPressed=await page.getByRole('button',{name:/Ultra mode/i}).getAttribute('aria-pressed');
checks.truthful=await page.getByText('Visual only · execution speed unchanged').isVisible();
checks.providerMounted=await page.locator('.model-trigger').count();
checks.noOverflow=await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth);
await page.close();
const mobile=await browser.newPage({viewport:{width:390,height:844}}); await mobile.goto('http://127.0.0.1:4173'); await mobile.getByRole('button',{name:/Fast mode/i}).click(); await mobile.waitForTimeout(520); await mobile.screenshot({path:`${out}/06-mobile-transition.png`}); await mobile.waitForTimeout(650); await mobile.screenshot({path:`${out}/07-mobile-fast.png`}); checks.mobileNoOverflow=await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth); await mobile.close();
const reduced=await browser.newPage({viewport:{width:1280,height:820},reducedMotion:'reduce'}); await reduced.goto('http://127.0.0.1:4173'); await reduced.getByRole('button',{name:/Fast mode/i}).click(); checks.reducedTransition=await reduced.locator('.fast-transition').count(); checks.reducedPressed=await reduced.getByRole('button',{name:/Fast mode/i}).getAttribute('aria-pressed'); await reduced.screenshot({path:`${out}/08-reduced.png`}); await reduced.close();
fs.writeFileSync(`${out}/checks.json`,JSON.stringify(checks,null,2)); await browser.close();
